### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HamzaIbrahimQ** [iamPiyushNagpal/Notes-App-Flutter#1]
hello man!
Thank you for this application,
but i have an error it's look like :
/C:/src/flutter%20sdk/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.3.4/lib/get_navigation/src/root/get_material_app.dart:297:15: Error: No named parameter with the name 'scrollBehavior'.
              scrollBehavior: scrollBehavior,
              ^^^^^^^^^^^^^^

i changed the version of get packege but i have the same problem!
can you help me please?

**Comment by iamPiyushNagpal** [comment]
> hello man!
> Thank you for this application,
> but i have an error it's look like :
> /C:/src/flutter%20sdk/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.3.4/lib/get_navigation/src/root/get_material_app.dart:297:15: Error: No named parameter with the name 'scrollBehavior'.
> scrollBehavior: scrollBehavior,
> ^^^^^^^^^^^^^^
> 
> i changed the version of get packege but i have the same problem!
> can you help me please?

Sorry Man, I will not be able to help you as I'm not in touch with App Development from almost 9-10 months.
